[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
]
[sources.allow-org]
github = ["ITRS-Group"]
[advisories]
ignore = ["RUSTSEC-2021-0145"] # Unaffected by this since xtender only runs on Linux.
