* Docker Compose service for Geneos Xtender Netprobe

One way of running an Xtender Netprobe is by using Docker Compose. The setup below assumes that you have already set up Docker as a systemd service and has been verified on Ubuntu 20.04.

Run all the commands below as root or using sudo.

** Log in to docker.itrsgroup.com
#+BEGIN_SRC bash
docker login docker.itrsgroup.com
#+END_SRC

** Pull the wanted version of the image
#+BEGIN_SRC bash
docker pull docker.itrsgroup.com/geneos-xtender-netprobe:24.06
#+END_SRC

** Create a directory /opt/itrs/xtender/docker if it doesn't already exist

#+BEGIN_SRC bash
mkdir -p /opt/itrs/xtender/docker
#+END_SRC

** Create the compose.yaml file /opt/itrs/xtender/docker/compose.yaml

#+BEGIN_SRC bash
cat <<EOF > /opt/itrs/xtender/docker/compose.yaml
version: "3"
services:
  xtender-netprobe:
    image: docker.itrsgroup.com/geneos-xtender-netprobe:24.06
    platform: linux/amd64
    ports:
      - "57036:7036"
      - "57136:7136"
      - "57137:7137"
      - "58125:8125"
      - "59137:9137"
      - "58125:8125/udp"
    volumes:
      - ./custom_plugins:/opt/itrs/xtender/plugins/custom:ro
      - ./custom_templates:/opt/itrs/xtender/templates/custom:ro
      - ./secret.key:/opt/itrs/xtender/secret.key:ro
      - ./secure:/netprobe/secure:ro
EOF
#+END_SRC

The volumes for *secret.key* and *secure* are not mandatory.
- *secret.key* would be the AES key used for encrypting any secret variables by the Gateway.
- *secure* would be the directory in which to store the TLS related files if a secure connection is wanted.

If you want to have a secure connection to your Gateway, add the TLS related files to the *secure* directory and use the following *compose.yaml* instead:

#+BEGIN_SRC bash
cat <<EOF > /opt/itrs/xtender/docker/compose.yaml
version: "3"
services:
  xtender-netprobe:
    image: docker.itrsgroup.com/geneos-xtender-netprobe:24.06
    platform: linux/amd64
    command: /netprobe/netprobe.linux_64 -ssl-certificate /netprobe/secure/netprobe.pem -secure -ssl-certificate-chain /netprobe/secure/chain.pem -ssl-certificate-key /netprobe/secure/netprobe.key
    ports:
      - "57036:7036"
      - "57136:7136"
      - "57137:7137"
      - "58125:8125"
      - "59137:9137"
      - "58125:8125/udp"
    volumes:
      - ./custom_plugins:/opt/itrs/xtender/plugins/custom:ro
      - ./custom_templates:/opt/itrs/xtender/templates/custom:ro
      - ./secret.key:/opt/itrs/xtender/secret.key:ro
      - ./secure:/netprobe/secure:ro
EOF
#+END_SRC

** Make sure the compose.yaml file has the right owner and permissions

#+BEGIN_SRC bash
chown -R root:root /opt/itrs/xtender/docker && chmod 644 /opt/itrs/xtender/docker/compose.yaml
#+END_SRC

** Create the /usr/lib/systemd/system/geneos-xtender-netprobe.service file

#+BEGIN_SRC bash
cat <<EOF > /usr/lib/systemd/system/geneos-xtender-netprobe.service
[Unit]
Description=geneos-xtender-netprobe service
Requires=docker.service
After=docker.service
[Service]
Type=simple
WorkingDirectory=/opt/itrs/xtender/docker
ExecStart=/usr/bin/docker compose -f /opt/itrs/xtender/docker/compose.yaml up
ExecStop=/usr/bin/docker compose -f /opt/itrs/xtender/docker/compose.yaml down
Restart=always
RestartSec=10s
[Install]
WantedBy=multi-user.target
EOF
#+END_SRC

** (Optional) If you're running a firewall, open the relevant ports, for example port 57036

*** Using firewalld
#+BEGIN_SRC bash
firewall-cmd --add-port=57036/tcp --permanent && firewall-cmd --reload
#+END_SRC

*** Using UFW
#+BEGIN_SRC bash
ufw allow 57036/tcp
#+END_SRC

** Enable and start the systemd service geneos-xtender-netprobe

#+BEGIN_SRC bash
systemctl daemon-reload && systemctl enable --now geneos-xtender-netprobe.service
#+END_SRC
